name: Periodic health check

on:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  health_check:
    runs-on: ubuntu-latest
    steps:
      - name: Check application health
        uses: Jtalk/url-health-check-action@v4
        with:
          url: https://fullstackopen-course-pqsy.onrender.com
          max-attempts: 3
          retry-delay: 10s
          follow-redirect: true
          
      - name: Health check success notification
        uses: rjstone/discord-webhook-notify@v2.2.1
        if: success()
        with:
          severity: info
          text: "Pokedex health check passed"
          description: "Application is running https://fullstackopen-course-pqsy.onrender.com"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}
          
      - name: Health check failure notification
        uses: rjstone/discord-webhook-notify@v2.2.1
        if: failure()
        with:
          severity: error
          text: "Pokedex health check failed"
          description: "Application is down at https://fullstackopen-course-pqsy.onrender.com"
          webhookUrl: ${{ secrets.DISCORD_WEBHOOK }}