name: Deployment pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches: [main]
    types: [opened, synchronize]

jobs:
  simple_deployment_pipeline:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install dependencies
        run: npm install
        working-directory: ./part11/pokedex
      - name: Install Playwright browsers
        run: npx playwright install --with-deps
        working-directory: ./part11/pokedex
      - name: lint
        run: npm run eslint
        working-directory: ./part11/pokedex
      - name: build
        run: npm run build
        working-directory: ./part11/pokedex
      - name: test
        run: npm run test
        working-directory: ./part11/pokedex
      - name: e2e-test
        run: npm run test:e2e
        working-directory: ./part11/pokedex
      - name: Trigger deployment
        run: curl https://api.render.com/deploy/srv-${{ secrets.RENDER_SERVICE_ID }}?key=${{ secrets.RENDER_API_KEY }}
        if: ${{ github.event_name == 'push' }}

  tag_release:
    needs: [simple_deployment_pipeline]
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'push' }}
    steps:
      - name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.73.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DEFAULT_BUMP: patch
          DRY_RUN: true